title: Team 5 | Electric Boogaloo
description: Rajiv Kommareddy (rrk64), Adam Macioszek (amm452), Kelsey Nedd (kan54), David Valley (drv34), Aaron Wisner (daw286), Christina Xu (chx3)
theme: jekyll-theme-midnight
